.\" Manpage for Terbot.
.\" Contact jake@jr0.org to correct errors or typos.
.TH man 8 "25 Dec 2019" "1.0" "rushnote man page"
.SH NAME
terbot \- switch termite themes from command line 
.SH DESCRIPTION
A fast way to switch termite themes all from the command line. 
.SH AUTHOR
Jake Roggenbuck, jake@jr0.org
